apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: exhort-dev
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: exhort-dev
    app.kubernetes.io/part-of: exhort
  name: exhort-devcupl
spec:
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: exhort-dev
    weight: null
status: {}
