apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: exhort-dev
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: exhort-dev
    app.kubernetes.io/part-of: exhort
  name: exhort-dev
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: exhort-dev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: exhort-dev
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-rromerom-tenant/exhort/exhort-dev@sha256:8a086be8b0292c6e89f5830fecdcc81d001d64613969d7fffa7cce08804d89b2
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
