apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: exhort-dev
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: exhort-dev
    app.kubernetes.io/part-of: exhort
  name: exhort-dev
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: exhort-dev
status:
  loadBalancer: {}
